# ubi 9.5-1742914212
FROM registry.access.redhat.com/ubi9-minimal@sha256:ac61c96b93894b9169221e87718733354dd3765dd4a62b275893c7ff0d876869

LABEL org.opencontainers.image.authors="CodeReady Containers <devtools-cdk@redhat.com>"

ENV AWS_CLI_VERSION 2.18.15
ENV AWS_CLI_URL https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip

RUN microdnf install -y openssh-clients sshpass unzip zip bash jq findutils wget \
    && curl ${AWS_CLI_URL} -o awscliv2.zip \
    && unzip awscliv2.zip \
    && ./aws/install \
    && microdnf clean all \
  	&& rm -rf /var/cache/yum \
    && mkdir /home/1001 \
    && chown -R 1001:0 /home/1001 \
    && chmod -R g=u /home/1001

USER 1001
ENV HOME /home/1001