# main
FROM quay.io/devtools-qe-incubator/deliverest:v0.0.7

LABEL org.opencontainers.image.authors="CRCQE <devtools-crc-qe@redhat.com>"

ARG OS 

ENV ASSETS_FOLDER=/opt/crc-support \
    OS=${OS} 

COPY /lib/${OS}/* ${ASSETS_FOLDER}/
