---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: snc-builder
  labels:
    app.kubernetes.io/version: "v1.0.2"
    redhat.com/product: openshift-local
    dev.lifecycle.io/phase: build
    openshift-local.redhat.com/component: bundle
  annotations:
    tekton.dev/pipelines.minVersion: "0.44.x"
    tekton.dev/categories: bundle
    tekton.dev/tags: openshift-local, bundle
    tekton.dev/displayName: "openshift local bundle"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This pipeline will bundles for Openshift Local:

    * bundles for all platforms and store them on an s3 compatible storage

  workspaces:
    - name: storage
    - name: s3-credentials
      description: |
        ocp secret holding the s3 credentials. Secret should be accessible to this task.
        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: XXXX
          labels:
            app.kubernetes.io/component: XXXX
        type: Opaque
        data:
          download-url: ${download_url}  
          upload-url: ${upload_url}  
          access-key: ${access_key}
          secret-key: ${secret_key}
    - name: ocp-pullsecret
      description: |
        crc secret name holding the pullsecret. This is only required if backed tested is crc preset

        secret should match following format:
        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${secret-name}
        type: Opaque
        data:
          pullsecret: ${pullsecret-value}
  
  params:
    # SNC runner params
    - name: arch
      description: arch for binaries x86_64 or arm64
      default: x86_64
    - name: runner-host-version
      description: Set the RHEL os version for snc-runner.
      default: '9.4'
    - name: bundle-type
      description: bundle to be built (openshift, microshift or okd)
      default: openshift
    # SNC repo params
    - name: snc-scm
      description: repository for snc project
      default: 'https://github.com/code-ready/snc.git'
    - name: snc-ref
      description: repository ref for snc project
      default: master
    - name: snc-pullrequest
      description: in case bundle build from PR
      default: "''"  
    # OCP params
    - name: ocp-index-url
      description: full url to download assets for an specific ocp version. Format base_url/ocp-version
      default: "''"  
    - name: ocp-extended-cert
      description: this param controls if apply patched images for KAO and KMCO to extend cert duration. Valid values are disabled or enabled
      default: disabled
    # Destination params
    - name: s3-bundles-path
      default: crc-bundle
    # Control
    - name: debug
      type: string
      description: control verbosity and keep instances after run for troubleshooting. 
      default: "false"
  
  tasks:
    - name: preparer
      taskSpec:
        description: This task will prepare the environment and data for being used within the pipeline
        params:
          - name: ocp-index-url
        results:
          - name: correlation
          - name: ocp-version
          - name: ocp-mirror 
        steps:
          - name: preparer
            image: registry.access.redhat.com/ubi9/ubi-minimal
            script: |
              #!/bin/sh
              echo -n $RANDOM$RANDOM | tee $(results.correlation.path)
              index_url=$(params.ocp-index-url)
              version=${index_url##*/}
              echo -n ${version} | tee $(results.ocp-version.path)
              echo -n ${index_url/\/$version/''} | tee $(results.ocp-mirror.path)
      params:
        - name: ocp-index-url
          value: $(params.ocp-index-url) 
    - name: provision-snc-runner
      runAfter:
        - preparer
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-developer/mapt:v0.9.9-tkn
          - name: name
            value: infra-aws-rhel
          - name: kind
            value: task
      params:
        - name: secret-aws-credentials
          value: aws-crcqe-bot
        - name: rh-credentials
          value: credentials-rh-subs-crcqe-prod
        - name: id
          value: $(tasks.preparer.results.correlation)
        - name: ownerKind
          value: PipelineRun
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
        - name: operation
          value: create
        - name: arch
          value: $(params.arch)
        - name: version
          value: $(params.runner-host-version)
        - name: profile-snc
          value: 'true'
        - name: debug
          value: $(params.debug)
        - name: tags
          value: "pipelinerunName=$(context.pipelineRun.name)"
        - name: nested-virt
          value: 'true'
        - name: spot
          value: 'true'
      timeout: "45m"
    - name: sync-provision 
      runAfter:
        - provision-snc-runner
      taskSpec:
        description: This task will get the host info
        params:
          - name: secret-host
          - name: workspace-resources-path
        volumes:
          - name: host-secret
            secret:
              secretName: $(params.secret-host)
          - name: storage
            persistentVolumeClaim:
              claimName: pipelines-data
        results:
          - name: host
          - name: username
          - name: key-filename
        steps:
          - name: sync-provision
            image: quay.io/rhqp/support-tools:v0.0.1
            volumeMounts:
              - name: host-secret
                mountPath: /opt/host-secret
              - name: storage
                mountPath: /opt/storage
            script: |
              #!/bin/bash
              set -x
              set -euo pipefail

              HOST_FILENAME=host
              USERNAME_FILENAME=username
              KEY_FILENAME=id_rsa

              workspace_path="/opt/host-secret"

              # Check files
              while [ ! -f "${workspace_path}/${HOST_FILENAME}" ]; do sleep 1; done
              while [ ! -f "${workspace_path}/${USERNAME_FILENAME}" ]; do sleep 1; done
              while [ ! -f "${workspace_path}/${KEY_FILENAME}" ]; do sleep 1; done
              
              mkdir -p /opt/storage/$(params.workspace-resources-path)
              # Set results
              cat "${workspace_path}/${HOST_FILENAME}" | tee $(results.host.path)   
              cat "${workspace_path}/${USERNAME_FILENAME}" | tee $(results.username.path)   
              cp "${workspace_path}/${KEY_FILENAME}" /opt/storage/$(params.workspace-resources-path)/${KEY_FILENAME}
              echo -n "${KEY_FILENAME}" | tee $(results.key-filename.path)  
      params:
        - name: secret-host
          value: $(tasks.provision-snc-runner.results.host-access-secret)
        - name: workspace-resources-path
          value: ci-snc-runner/$(tasks.preparer.results.correlation)
      timeout: "10m"
    - name: build-bundle
      runAfter:
        - provision-snc-runner
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/crc-org/ci-definitions.git
          - name: revision
            value: snc-runner-v1.0.2
          - name: pathInRepo
            value: snc-runner/tkn/task.yaml
      params:
      - name: workspace-resources-path
        value: ci-snc-runner/$(tasks.preparer.results.correlation)
      - name: host
        value: $(tasks.sync-provision.results.host)
      - name: username
        value: $(tasks.sync-provision.results.username)
      - name: key
        value: $(tasks.sync-provision.results.key-filename)
      - name: scm
        value: $(params.snc-scm) 
      - name: ref
        value: $(params.snc-ref) 
      - name: pr
        value: $(params.snc-pullrequest) 
      - name: ocp-version
        value: $(tasks.preparer.results.ocp-version)
      - name: ocp-mirror
        value: $(tasks.preparer.results.ocp-mirror)
      - name: ocp-extended-cert
        value: $(params.ocp-extended-cert)
      - name: s3-path
        value: $(params.s3-bundles-path)/$(tasks.preparer.results.ocp-version)
      - name: debug
        value: $(params.debug) 
      workspaces:
      - name: storage
        workspace: storage
      - name: s3-credentials
        workspace: s3-credentials
      - name: ocp-pullsecret
        workspace: ocp-pullsecret
      timeout: "185m" 
  finally:
    - name: decomission-snc-runner
      when:
        - input: $(params.debug)
          operator: in
          values: ["false"]
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-developer/mapt:v0.9.9-tkn
          - name: name
            value: infra-aws-rhel
          - name: kind
            value: task
      params:
        - name: secret-aws-credentials
          value: aws-crcqe-bot
        - name: rh-credentials
          value: credentials-rh-subs-crcqe-prod
        - name: id
          value: $(tasks.preparer.results.correlation)
        - name: ownerKind
          value: PipelineRun
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
        - name: operation
          value: destroy
        - name: ws-output-path
          value: ci-snc-runner/$(tasks.preparer.results.correlation)
        - name: debug
          value: $(params.debug)
      timeout: "45m" 
    - name: print-decomission
      when:
        - input: $(params.debug)
          operator: in
          values: ["true"]
      taskSpec:
        params:
          - name: correlation
        steps:
          - name: print
            image: registry.access.redhat.com/ubi9/ubi-minimal
            script: |
              #!/bin/sh

              set -exuo pipefail

              touch pipelinerun.yaml
              
              cat <<EOF > pipelinerun.yaml
              ---
              apiVersion: tekton.dev/v1beta1
              kind: TaskRun
              metadata:
                generateName: decomission-snc-runner-$(params.correlation)
              spec:
                taskRef:
                  resolver: bundles
                  params:
                    - name: bundle
                      value: quay.io/redhat-developer/mapt:v0.9.9-tkn
                    - name: pathInRepo
                      value: tkn/infra-aws-rhel.yaml
                    - name: kind
                      value: task 
                params:
                  - name: secret-aws-credentials
                    value: aws-crcqe-bot
                  - name: rh-credentials
                    value: credentials-rh-subs-crcqe-prod
                  - name: id
                    value: $(params.correlation)
                  - name: ownerKind
                    value: PipelineRun
                  - name: operation
                    value: destroy
                  - name: ws-output-path
                    value: ci-snc-runner/$(params.correlation)
                timeout: "20m" 
              EOF

              cat pipelinerun.yaml
      params:
        - name: correlation
          value: $(tasks.preparer.results.correlation)

      

